### PR TITLE
Add "discontinued" standing, add missing specs for Bikeshed

### PR DESCRIPTION
**Pull request by tidoust**
This update adds a new `discontinued` value to the `standing` property for specs that are still in the list for some reason (typically because other specs still reference terms and sections they define in informative prose), but whose development has been discontinued. Specs whose status is "Discontinued Draft" end up with a `discontinued` standing.

This affects DNT in the current (before this update) list. The spec will be filtered out of the `browser-specs` package as a result. That seems a good thing.

This update also adds CSS specs that are needed for cross-referencing purpose in Bikeshed, as requested in:
https://github.com/tabatkins/bikeshed/issues/2431#issuecomment-1373992354

New specs are either:
- discontinued specs such as selectors-nonelement-1, DOM-Level-2-Style
- older versions of some specs such as css-color-3, css-contain-1, css-ui-3
- unofficial drafts that have not yet been completely adopted by the CSS WG such as css-color-6, css-color-hdr, css-conditional-values-1
- the latest CSS snapshot css-2022.

Two comments on "status, categories or standing?":
- Another approach for "Discontinued Draft" specs would be to say that they are in good standing and exclude them from the browser-specs package simply because they are discontinued.
- This will add css-2022 to the browser-specs package. I think that's fine. If we do not want that, we could perhaps remove the spec from the `browser` category.

<details>
  <summary>Changes to index.json</summary>

  Note series info for css-color is wrong simply because other levels were not taken into account when generating these changes.

  ```json
  [
    {
      "url": "https://drafts.csswg.org/css-color-6/",
      "seriesComposition": "delta",
      "shortname": "css-color-6",
      "series": {
        "shortname": "css-color",
        "currentSpecification": "css-color-3",
        "title": "CSS Color",
        "shortTitle": "CSS Color",
        "releaseUrl": "https://www.w3.org/TR/css-color/",
        "nightlyUrl": "https://drafts.csswg.org/css-color/"
      },
      "seriesVersion": "6",
      "seriesPrevious": "css-color-3",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "nightly": {
        "url": "https://drafts.csswg.org/css-color-6/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-color-6/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-color-6/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Color Module Level 6",
      "source": "spec",
      "shortTitle": "CSS Color 6",
      "categories": [
        "browser"
      ],
      "standing": "good",
      "tests": {
        "repository": "https://github.com/web-platform-tests/wpt",
        "testPaths": [
          "css/css-color"
        ]
      }
    },
    {
      "url": "https://drafts.csswg.org/css-color-hdr/",
      "seriesComposition": "full",
      "shortname": "css-color-hdr",
      "series": {
        "shortname": "css-color-hdr",
        "currentSpecification": "css-color-hdr",
        "title": "CSS Color HDR",
        "shortTitle": "CSS Color HDR",
        "nightlyUrl": "https://drafts.csswg.org/css-color-hdr/"
      },
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "nightly": {
        "url": "https://drafts.csswg.org/css-color-hdr/",
        "status": "Unofficial Proposal Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-color-hdr/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-color-hdr/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Color HDR Module Level 1",
      "source": "spec",
      "shortTitle": "CSS Color HDR 1",
      "categories": [
        "browser"
      ],
      "standing": "pending"
    },
    {
      "url": "https://drafts.csswg.org/css-conditional-values-1/",
      "seriesComposition": "full",
      "shortname": "css-conditional-values-1",
      "series": {
        "shortname": "css-conditional-values",
        "currentSpecification": "css-conditional-values-1",
        "title": "CSS Conditional Values",
        "shortTitle": "CSS Conditional Values",
        "nightlyUrl": "https://drafts.csswg.org/css-conditional-values/"
      },
      "seriesVersion": "1",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "nightly": {
        "url": "https://drafts.csswg.org/css-conditional-values-1/",
        "status": "Unofficial Proposal Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-conditional-values-1/",
          "https://w3c.github.io/csswg-drafts/css-conditional-values/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-conditional-values-1/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Conditional Values Module Level 1",
      "source": "spec",
      "shortTitle": "CSS Conditional Values 1",
      "categories": [
        "browser"
      ],
      "standing": "pending"
    },
    {
      "url": "https://drafts.csswg.org/css-forms-1/",
      "seriesComposition": "full",
      "shortname": "css-forms-1",
      "series": {
        "shortname": "css-forms",
        "currentSpecification": "css-forms-1",
        "title": "CSS Form Styling",
        "shortTitle": "CSS Form Styling",
        "nightlyUrl": "https://drafts.csswg.org/css-forms/"
      },
      "seriesVersion": "1",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "nightly": {
        "url": "https://drafts.csswg.org/css-forms-1/",
        "status": "A Collection of Interesting Ideas",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-forms-1/",
          "https://w3c.github.io/csswg-drafts/css-forms/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-forms-1/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Form Styling Module Level 1",
      "source": "spec",
      "shortTitle": "CSS Form Styling 1",
      "categories": [
        "browser"
      ],
      "standing": "pending"
    },
    {
      "url": "https://www.w3.org/TR/css-2022/",
      "seriesComposition": "full",
      "shortname": "css-2022",
      "series": {
        "shortname": "css",
        "currentSpecification": "css-2022",
        "title": "CSS Snapshot",
        "shortTitle": "CSS Snapshot",
        "releaseUrl": "https://www.w3.org/TR/css/",
        "nightlyUrl": "https://drafts.csswg.org/css/"
      },
      "seriesVersion": "2022",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/css-2022/",
        "status": "Draft Note",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/css-2022/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-2022/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-2022/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Snapshot 2022",
      "source": "w3c",
      "shortTitle": "CSS Snapshot 2022",
      "categories": [
        "browser"
      ],
      "standing": "good"
    },
    {
      "url": "https://www.w3.org/TR/css-color-3/",
      "seriesComposition": "full",
      "shortname": "css-color-3",
      "series": {
        "shortname": "css-color",
        "currentSpecification": "css-color-3",
        "title": "CSS Color",
        "shortTitle": "CSS Color",
        "releaseUrl": "https://www.w3.org/TR/css-color/",
        "nightlyUrl": "https://drafts.csswg.org/css-color/"
      },
      "seriesVersion": "3",
      "seriesNext": "css-color-6",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/css-color-3/",
        "status": "Recommendation",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/css-color-3/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-color-3/",
          "https://w3c.github.io/csswg-drafts/css-color/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-color-3/Overview.html",
        "filename": "Overview.html"
      },
      "title": "CSS Color Module Level 3",
      "source": "w3c",
      "shortTitle": "CSS Color 3",
      "categories": [
        "browser"
      ],
      "standing": "good",
      "tests": {
        "repository": "https://github.com/web-platform-tests/wpt",
        "testPaths": [
          "css/css-color"
        ]
      }
    },
    {
      "url": "https://www.w3.org/TR/css-contain-1/",
      "seriesComposition": "full",
      "shortname": "css-contain-1",
      "series": {
        "shortname": "css-contain",
        "currentSpecification": "css-contain-1",
        "title": "CSS Containment",
        "shortTitle": "CSS Containment",
        "releaseUrl": "https://www.w3.org/TR/css-contain/",
        "nightlyUrl": "https://drafts.csswg.org/css-contain/"
      },
      "seriesVersion": "1",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/css-contain-1/",
        "status": "Recommendation",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/css-contain-1/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-contain-1/",
          "https://w3c.github.io/csswg-drafts/css-contain/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-contain-1/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Containment Module Level 1",
      "source": "w3c",
      "shortTitle": "CSS Containment 1",
      "categories": [
        "browser"
      ],
      "standing": "good",
      "tests": {
        "repository": "https://github.com/web-platform-tests/wpt",
        "testPaths": [
          "css/css-contain"
        ]
      }
    },
    {
      "url": "https://www.w3.org/TR/css-grid-1/",
      "seriesComposition": "full",
      "shortname": "css-grid-1",
      "series": {
        "shortname": "css-grid",
        "currentSpecification": "css-grid-1",
        "title": "CSS Grid Layout",
        "shortTitle": "CSS Grid Layout",
        "releaseUrl": "https://www.w3.org/TR/css-grid/",
        "nightlyUrl": "https://drafts.csswg.org/css-grid/"
      },
      "seriesVersion": "1",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/css-grid-1/",
        "status": "Candidate Recommendation Draft",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/css-grid-1/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-grid-1/",
          "https://w3c.github.io/csswg-drafts/css-grid/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-grid-1/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Grid Layout Module Level 1",
      "source": "w3c",
      "shortTitle": "CSS Grid Layout 1",
      "categories": [
        "browser"
      ],
      "standing": "good",
      "tests": {
        "repository": "https://github.com/web-platform-tests/wpt",
        "testPaths": [
          "css/css-grid"
        ]
      }
    },
    {
      "url": "https://www.w3.org/TR/css-ui-3/",
      "seriesComposition": "full",
      "shortname": "css-ui-3",
      "series": {
        "shortname": "css-ui",
        "currentSpecification": "css-ui-3",
        "title": "CSS Basic User Interface",
        "shortTitle": "CSS Basic User Interface",
        "releaseUrl": "https://www.w3.org/TR/css-ui/",
        "nightlyUrl": "https://drafts.csswg.org/css-ui/"
      },
      "seriesVersion": "3",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/css-ui-3/",
        "status": "Recommendation",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/css-ui-3/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-ui-3/",
          "https://w3c.github.io/csswg-drafts/css-ui/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-ui-3/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Basic User Interface Module Level 3 (CSS3 UI)",
      "source": "w3c",
      "shortTitle": "CSS3 UI",
      "categories": [
        "browser"
      ],
      "standing": "good",
      "tests": {
        "repository": "https://github.com/web-platform-tests/wpt",
        "testPaths": [
          "css/css-ui"
        ]
      }
    },
    {
      "url": "https://www.w3.org/TR/css-writing-modes-3/",
      "seriesComposition": "full",
      "shortname": "css-writing-modes-3",
      "series": {
        "shortname": "css-writing-modes",
        "currentSpecification": "css-writing-modes-3",
        "title": "CSS Writing Modes",
        "shortTitle": "CSS Writing Modes",
        "releaseUrl": "https://www.w3.org/TR/css-writing-modes/",
        "nightlyUrl": "https://drafts.csswg.org/css-writing-modes/"
      },
      "seriesVersion": "3",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/css-writing-modes-3/",
        "status": "Recommendation",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/css-writing-modes-3/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/css-writing-modes-3/",
          "https://w3c.github.io/csswg-drafts/css-writing-modes/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "css-writing-modes-3/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "CSS Writing Modes Level 3",
      "source": "w3c",
      "shortTitle": "CSS Writing Modes 3",
      "categories": [
        "browser"
      ],
      "standing": "good",
      "tests": {
        "repository": "https://github.com/web-platform-tests/wpt",
        "testPaths": [
          "css/css-writing-modes"
        ]
      }
    },
    {
      "url": "https://www.w3.org/TR/DOM-Level-2-Style/",
      "seriesComposition": "full",
      "shortname": "DOM-Level-2-Style",
      "series": {
        "shortname": "DOM-Style",
        "currentSpecification": "DOM-Level-2-Style",
        "title": "Document Object Model (DOM) Style",
        "shortTitle": "DOM",
        "releaseUrl": "https://www.w3.org/TR/DOM-Style/",
        "nightlyUrl": "https://www.w3.org/TR/DOM-Style/"
      },
      "nightly": {
        "url": "https://www.w3.org/TR/DOM-Level-2-Style/",
        "status": "Editor's Draft",
        "alternateUrls": [],
        "filename": "Overview.html"
      },
      "organization": "W3C",
      "groups": [
        {
          "name": "DOM Working Group",
          "url": "https://www.w3.org/DOM/Group/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/DOM-Level-2-Style/",
        "status": "Discontinued Draft",
        "filename": "Overview.html"
      },
      "title": "Document Object Model (DOM) Level 2 Style Specification",
      "source": "w3c",
      "shortTitle": "DOM",
      "categories": [
        "browser"
      ],
      "standing": "discontinued"
    },
    {
      "url": "https://www.w3.org/TR/mediaqueries-3/",
      "seriesComposition": "full",
      "shortname": "mediaqueries-3",
      "series": {
        "shortname": "mediaqueries",
        "currentSpecification": "mediaqueries-3",
        "title": "Media Queries",
        "shortTitle": "Media Queries",
        "releaseUrl": "https://www.w3.org/TR/mediaqueries/",
        "nightlyUrl": "https://drafts.csswg.org/mediaqueries/"
      },
      "seriesVersion": "3",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/mediaqueries-3/",
        "status": "Recommendation",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/mediaqueries-3/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/mediaqueries-3/",
          "https://w3c.github.io/csswg-drafts/mediaqueries/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "mediaqueries-3/Overview.html",
        "filename": "Overview.html"
      },
      "title": "Media Queries Level 3",
      "source": "w3c",
      "shortTitle": "Media Queries 3",
      "categories": [
        "browser"
      ],
      "standing": "good",
      "tests": {
        "repository": "https://github.com/web-platform-tests/wpt",
        "testPaths": [
          "css/mediaqueries"
        ]
      }
    },
    {
      "url": "https://www.w3.org/TR/selectors-3/",
      "seriesComposition": "full",
      "shortname": "selectors-3",
      "series": {
        "shortname": "selectors",
        "currentSpecification": "selectors-3",
        "title": "Selectors",
        "shortTitle": "Selectors",
        "releaseUrl": "https://www.w3.org/TR/selectors/",
        "nightlyUrl": "https://drafts.csswg.org/selectors/"
      },
      "seriesVersion": "3",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/selectors-3/",
        "status": "Recommendation",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/selectors-3/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/selectors-3/",
          "https://w3c.github.io/csswg-drafts/selectors/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "selectors-3/Overview.src.html",
        "filename": "Overview.html"
      },
      "title": "Selectors Level 3",
      "source": "w3c",
      "shortTitle": "Selectors 3",
      "categories": [
        "browser"
      ],
      "standing": "good",
      "tests": {
        "repository": "https://github.com/web-platform-tests/wpt",
        "testPaths": [
          "css/selectors"
        ]
      }
    },
    {
      "url": "https://www.w3.org/TR/selectors-nonelement-1/",
      "seriesComposition": "full",
      "shortname": "selectors-nonelement-1",
      "series": {
        "shortname": "selectors-nonelement",
        "currentSpecification": "selectors-nonelement-1",
        "title": "Non-element Selectors",
        "shortTitle": "Non-element Selectors",
        "releaseUrl": "https://www.w3.org/TR/selectors-nonelement/",
        "nightlyUrl": "https://drafts.csswg.org/selectors-nonelement/"
      },
      "seriesVersion": "1",
      "organization": "W3C",
      "groups": [
        {
          "name": "Cascading Style Sheets (CSS) Working Group",
          "url": "https://www.w3.org/Style/CSS/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/selectors-nonelement-1/",
        "status": "Discontinued Draft",
        "filename": "Overview.html"
      },
      "nightly": {
        "url": "https://drafts.csswg.org/selectors-nonelement-1/",
        "status": "Editor's Draft",
        "alternateUrls": [
          "https://w3c.github.io/csswg-drafts/selectors-nonelement-1/",
          "https://w3c.github.io/csswg-drafts/selectors-nonelement/"
        ],
        "repository": "https://github.com/w3c/csswg-drafts",
        "sourcePath": "selectors-nonelement-1/Overview.bs",
        "filename": "Overview.html"
      },
      "title": "Non-element Selectors Module Level 1",
      "source": "w3c",
      "shortTitle": "Non-element Selectors 1",
      "categories": [
        "browser"
      ],
      "standing": "discontinued"
    }
  ]
  ```json
</details>

### CODE REVIEW

**Review by dontcallmedom — APPROVED** [review]
Do-Not-Track being removed from browser-specs will likely impact [its usage in MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack); but that's probably fine, it can always be added as part of their exception list.

**Comment by tidoust** [comment]
> Do-Not-Track being removed from browser-specs will likely impact [its usage in MDN](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack); but that's probably fine, it can always be added as part of their exception list.

If MDN only needs to lookup specs in browser-specs, I wonder whether they could rather depend on web-specs instead of on browser-specs? That should not create any blocking issue on their side. And we could perhaps handle their exception list directly within web-specs.

**Comment by Elchi3** [comment]
Yes, this affects us. https://github.com/mdn/browser-compat-data/blob/main/test/linter/test-spec-urls.ts#L15 is our exception list btw. Upon trying to upgrade browser-specs, the DNT spec can't by found anymore. https://github.com/mdn/browser-compat-data/actions/runs/3882672708/jobs/6623097296#step:5:42

**Comment by Elchi3** [comment]
Switching to web-specs fixes it, looks like. Should we use that instead then?

**Comment by tidoust** [comment]
Yes, web-specs is a small super-set of browser-specs and it should be a drop-in replacement for MDN (unless you need a list of specs restricted to those really targeted at browsers somewhere? It's easy to get the browser-specs list from web-specs in any case, just filter out specs that don't have `browser` in `categories` and those for which `standing` is not `good`).

That will give you back the DNT spec, and shouldn't add any problematic spec.

Quickly looking at the exception list, I note that:
- We have https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-expect-ct-08 under https://www.rfc-editor.org/rfc/rfc9163. Any reason to keep the older draft URL?
- We have https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers-05 under https://datatracker.ietf.org/doc/html/draft-ietf-httpbis-digest-headers to avoid having to update the revision number (current revision is 10).
- `css-color-6` was added to browser-specs
- for https://w3c.github.io/csswg-drafts/css2, #730 was fixed.

**Comment by Elchi3** [comment]
Thanks @tidoust! 💯 
I'm switching MDN and BCD to web-specs and I also updated BCD's exception list based on your input.

**Pull request merged**
