### PR TITLE
Add WHATWG Web Sockets standard

### PR DESCRIPTION
**Pull request by dontcallmedom**
detected by find-specs once #450 is merged

### CODE REVIEW

**Review by tidoust — APPROVED** [review]
At the browser-specs level, change seems good and warranted.

That said, the HTML spec still contains [the Web Sockets](https://html.spec.whatwg.org/multipage/web-sockets.html) section. I suppose that this is temporary? In the meantime, definitions and IDL will be duplicated in Webref.

**Comment by dontcallmedom** [comment]
indeed, but I'm hoping https://github.com/whatwg/html/pull/7414 will get merged quickly so that we don't have patch it before the next release

**Comment by dontcallmedom** [comment]
I'll merge this when that PR lands

**Comment by tidoust** [comment]
Merging as Web Sockets section was removed from HTML yesterday.

**Pull request merged**
