### PR TITLE
Update documentation re repository.nightly availability

### LINKED ISSUE #331: IETF specs provides no `nightly.repository`
It's contradictory to https://github.com/w3c/browser-specs#nightlyrepository.

>The `repository` property is always set.

### PR DESCRIPTION
**Pull request by dontcallmedom**
close #331
Follow up to https://github.com/w3c/browser-specs/pull/325/commits/687e149c501167e2a189c28da28f648f80717fe6

### CODE REVIEW

**Comment by dontcallmedom** [comment]
Since we broke a commitment, it does feel like this should have been a major release…

**Comment by dontcallmedom** [comment]
(I thought we didn't have such a commitment since the schema didn't enforce it - maybe another worth looking at more generally)

**Comment by saschanaz** [comment]
Note that `sourcePath` is now also undefined-able too

**Review by tidoust — APPROVED** [review]
> Since we broke a commitment, it does feel like this should have been a major release…

True. That's a bit too late but I'll issue a new major release.

**Pull request merged**
