### PR TITLE
Add missing nightly.url for test-methodology doc

### PR DESCRIPTION
**Pull request by dontcallmedom**

### CODE REVIEW

**Comment by dontcallmedom** [comment]
```json
{
  "added": [
    {
      "url": "https://www.w3.org/TR/test-methodology/",
      "seriesComposition": "full",
      "shortname": "test-methodology",
      "series": {
        "shortname": "test-methodology",
        "currentSpecification": "test-methodology",
        "title": "A Method for Writing Testable Conformance Requirements",
        "shortTitle": "A Method for Writing Testable Conformance Requirements",
        "releaseUrl": "https://www.w3.org/TR/test-methodology/",
        "nightlyUrl": "https://www.w3.org/TR/test-methodology/"
      },
      "nightly": {
        "url": "https://www.w3.org/TR/test-methodology/",
        "alternateUrls": [],
        "repository": "https://github.com/w3c/test-methodology",
        "filename": "Overview.html"
      },
      "organization": "W3C",
      "groups": [
        {
          "name": "Mobile Web Test Suites Working Group",
          "url": "https://www.w3.org/2005/MWI/Tests/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/test-methodology/",
        "filename": "Overview.html"
      },
      "title": "A Method for Writing Testable Conformance Requirements",
      "source": "w3c",
      "shortTitle": "A Method for Writing Testable Conformance Requirements",
      "categories": [
        "browser"
      ]
    }
  ],
  "updated": [],
  "deleted": []
}
```
(maybe build-diff should be run automatically on pull requests that touch specs.json?)

**Comment by dontcallmedom** [comment]
looking at the diff - probably should also be removed from the browser category, will update

**Comment by dontcallmedom** [comment]
```json
{
  "added": [],
  "updated": [
    {
      "url": "https://www.w3.org/TR/test-methodology/",
      "seriesComposition": "full",
      "shortname": "test-methodology",
      "series": {
        "shortname": "test-methodology",
        "currentSpecification": "test-methodology",
        "title": "A Method for Writing Testable Conformance Requirements",
        "shortTitle": "A Method for Writing Testable Conformance Requirements",
        "releaseUrl": "https://www.w3.org/TR/test-methodology/",
        "nightlyUrl": "https://www.w3.org/TR/test-methodology/"
      },
      "nightly": {
        "url": "https://www.w3.org/TR/test-methodology/",
        "alternateUrls": [],
        "repository": "https://github.com/w3c/test-methodology",
        "filename": "Overview.html"
      },
      "categories": [],
      "organization": "W3C",
      "groups": [
        {
          "name": "Mobile Web Test Suites Working Group",
          "url": "https://www.w3.org/2005/MWI/Tests/"
        }
      ],
      "release": {
        "url": "https://www.w3.org/TR/test-methodology/",
        "filename": "Overview.html"
      },
      "title": "A Method for Writing Testable Conformance Requirements",
      "source": "w3c",
      "shortTitle": "A Method for Writing Testable Conformance Requirements"
    }
  ],
  "deleted": []
}
```

**Comment by tidoust** [comment]
@dontcallmedom, FWIW, the build-diff tool reports a `repository` above likely because you did not set a `GH_TOKEN` token locally (used to assess whether the repository really exists).

**Pull request merged**
