### PR TITLE
Add WebGL extensions

### LINKED ISSUE #156: WebGL extensions
There are a lot of WebGL extensions that define bits of Web IDL, at some of which are implemented in browsers:
https://www.khronos.org/registry/webgl/extensions/

Adding all of these manually would be a bit tedious, is there another way we could handle these?

### PR DESCRIPTION
**Pull request by dontcallmedom**
close #156 

I have checked on some of the extension specs that extract-webidl works for them. I don't know if there are other checks to run for reffy-compatibility.

We could add a detector to find-specs; I haven't determined whether it is worth the effort.

### CODE REVIEW

**Review by tidoust — APPROVED** [review]
Looks fine but I note that there are a number of these specifications that have been "Promoted to core and no longer available as an extension in WebGL API 2.0 specification".

The IDL they define always seems prefixed/suffixed so that won't create duplicate IDL issues. That just begs the question: shouldn't the extension specs that have been promoted to core be considered obsolete (and not be included)?

**Comment by dontcallmedom** [comment]
great catch!

I can't find any clear indication of the "promoted to core" status - where do you find it out?

**Comment by Elchi3** [comment]
Not sure what @tidoust is referring to exactly but jumping in from my own experience with WebGL extensions :) 
See e.g. https://www.khronos.org/registry/webgl/extensions/ANGLE_instanced_arrays/ under "Dependencies".

When I documented this, I also first thought that a bunch of stuff is obsoleted with WebGL 2, but WebGL is versioned and the versions 1 and 2 co-exist actually. So, these extensions are still valid and needed if you write applications for WebGL 1 contexts.
That said, I wouldn't consider these extensions obsolete. Depending on the context you use, you either have these things available in WebGL 2 core, or your get them via an extension in a WebGL 1 context.

**Comment by tidoust** [comment]
Right, I just RTFM-ed and saw the "Dependencies" sections, @dontcallmedom.

Given @Elchi3's feedback and since we have both WebGL 1 and WebGL 2 in browser-specs, it makes sense to me to keep the extensions that have been incroporated in WebGL 2.

**Pull request merged**
