### PR TITLE
Add fingerprinting-guidance to the list of specs.

### PR DESCRIPTION
**Pull request by jyasskin**

### CODE REVIEW

**Review by dontcallmedom — CHANGES_REQUESTED** [review]
hi @jyasskin - the Fingerprinting Guidance document doesn't a prori fulfills the [requirements for addition here](https://github.com/w3c/browser-specs#spec-selection-criteria), since it's not a spec that browsers would implement. Can you say more about the motivation of having added?

Thanks!

**Review by tidoust — APPROVED** [review]
We did not include the spec in the initial list because it is a Note that is not "implemented" per se and we hadn't fleshed out [spec selection criteria](https://github.com/w3c/browser-specs/#spec-selection-criteria) at the time (see #26 and https://github.com/w3c/browser-specs/issues/50#issuecomment-645489318) .

These criteria now mention "guidelines from horizontal activities such as accessibility, internationalization, privacy and security" as a good motivation for inclusion, and it makes sense for specs to reference the browser fingerprinting spec. So +1 from me.

@jyasskin FYI, I note that the spec only exports 2 definitions for the time being:
- [browser fingerprinting](https://w3c.github.io/fingerprinting-guidance/#dfn-browser-fingerprinting)
- [fingerprinting surface](https://w3c.github.io/fingerprinting-guidance/#dfn-fingerprinting-surface)

There could be other terms worth exporting so that other specs may cross-reference them such as [passive fingerprinting](https://w3c.github.io/fingerprinting-guidance/#dfn-passive-fingerprinting), [active fingerprinting](https://w3c.github.io/fingerprinting-guidance/#dfn-active-fingerprinting) and [cookie-like fingerprinting](https://w3c.github.io/fingerprinting-guidance/#dfn-cookie-like-fingerprinting).

It may also be useful to be add the best practices themselves to the xref database, I'm not sure there is a good mechanism for that for the time being though.

**Review by dontcallmedom — APPROVED** [review]

**Comment by tidoust** [comment]
@dontcallmedom I note that I hadn't seen your feedback before I provided mine. If you believe that we need to give it more thoughts, that's fine with me. Sooner or later, we'll hit the "spec not for browsers but needs to be in the list coz' that other spec needs to reference terms" problem 🙀

**Comment by dontcallmedom** [comment]
> @dontcallmedom I note that I hadn't seen your feedback before I provided mine. If you believe that we need to give it more thoughts, that's fine with me. Sooner or later, we'll hit the "spec not for browsers but needs to be in the list coz' that other spec needs to reference terms" problem scream_cat

That was indeed kind of what I were I was going - if indeed the need is/was mostly in terms of expanding the set of available definitions, this might be sign that time has come to bite that bullet. But I also recognize your argument about the updated set of acceptable documents applies, so :shrug:

**Comment by jyasskin** [comment]
Sorry for taking a while to reply: my reasoning was what @tidoust [described](https://github.com/w3c/browser-specs/pull/326#pullrequestreview-698006462), that other implemented specs need to refer to the couple exported definitions. The other plausible terms aren't exported yet just because other specs happen not to have needed to refer to them. I don't edit that document, but I suspect its editor will accept such pull requests when they're needed. I think we'd add the best practices themselves similarly to how https://w3ctag.github.io/ethical-web-principles/#oneweb does it: just make the title a `dfn`.

**Pull request merged**
